services:
  zest-api:
    build: .
    ports:
      - 8080:8080
    networks:
      - monitoring
      - default
    volumes:
      - type: bind
        source: ./internal/reddit/store.db
        target: /internal/reddit/store.db
      - type: bind
        source: ./internal/metacritic/store.db
        target: /internal/metacritic/store.db
      - type: bind
        source: ./secrets/config.json
        target: /secrets/config.json
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - default
volumes:
  prometheus-data:


networks:
  monitoring:
    driver: bridge
