services:
  zest-api:
    container_name: zest-api
    build: .
    ports:
      - 8080:8080
    networks:
      - monitoring
      - default
    environment:
      - WITH_AUTH=true
    volumes:
      - type: bind
        source: ./.remote/
        target: /.remote/
      - type: bind
        source: ./secrets/
        target: /secrets/
    depends_on:
      - redis
      - tempo
      - postgres
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - monitoring
      - default
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - monitoring
      - default
    environment:
      - POSTGRES_USER=zeke
      - POSTGRES_PASSWORD=reyna
      - POSTGRES_DB=zest
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080
    networks:
      - monitoring
      - default
  prometheus:
    profiles: [ "monitoring" ]
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - default
    depends_on:
      - zest-api
  grafana:
    profiles: [ "monitoring" ]
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
      - default
  tempo:
    profiles: [ "monitoring" ]
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    restart: unless-stopped
    volumes:
      - tempo-data:/tmp/tempo
      - ./configs/tempo.yaml:/etc/tempo.yaml
    networks:
      - monitoring
      - default
    ports:
      - 3200:3200 # tempo
      - 9095:9095 # tempo grpc
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
  nginx:
    profiles: [ "prod" ]
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ./configs/nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www/:/var/www/certbot:ro
    networks:
      - monitoring
      - default
    depends_on:
      - zest-api
  certbot:
    profiles: [ "certs" ]
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www/:/var/www/certbot:rw
    networks:
      - monitoring
      - default
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email reynaezekiel@gmail.com --agree-tos --no-eff-email -d api.zekereyna.dev

volumes:
  prometheus-data:
  certbot-etc:
  certbot-var:
  grafana-storage:
  tempo-data:
  pgdata:


networks:
  monitoring:
    driver: bridge
