include:
  - compose/monitoring.yaml
  - compose/aux.yaml
services:
  zest-api:
    container_name: zest-api
    build: .
    ports:
      - 8080:8080
    environment:
      - WITH_AUTH=true
    volumes:
      - type: bind
        source: ./secrets/
        target: /secrets/
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=zeke
      - POSTGRES_PASSWORD=reyna
      - POSTGRES_DB=zest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
