services:
  zest-api:
    build: .
    ports:
      - 8080:8080
    networks:
      - monitoring
      - default
    volumes:
      - type: bind
        source: ./internal/reddit/store.db
        target: /internal/reddit/store.db
      - type: bind
        source: ./internal/metacritic/store.db
        target: /internal/metacritic/store.db
      - type: bind
        source: ./secrets/config.json
        target: /secrets/config.json
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - default
    depends_on:
      - zest-api
  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www/:/var/www/certbot:ro
    networks:
      - monitoring
      - default
    depends_on:
      - zest-api
  certbot:
    profiles: [ "certs" ]
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www/:/var/www/certbot:rw
    networks:
      - monitoring
      - default
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email reynaezekiel@gmail.com --agree-tos --no-eff-email -d api.zekereyna.dev

volumes:
  prometheus-data:
  certbot-etc:
  certbot-var:


networks:
  monitoring:
    driver: bridge
