parameters: {}
environment: {}
packages:
    - name: zest
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: refresh
          binary: false
          main: ""
          runtime: go:1.20
          web: true
          webSecure: false
          parameters: {}
          annotations: {}
          limits: {}
          environment:
            ZEST_USERNAME: "${ZEST_USERNAME}"
            ZEST_PASSWORD: "${ZEST_PASSWORD}"
          # the following triggers don't work per https://github.com/digitalocean/doctl/issues/1474
          # but keeping for reference!
          triggers:
            - name: refresh-reddit-hourly
              sourceType: scheduler
              sourceDetails:
                cron: "0 * * * *"
                withBody:
                  resource: 'reddit'
            - name: refresh-metacritic-daily
              sourceType: scheduler
              sourceDetails:
                cron: "0 8 * * *"
                withBody:
                  resource: 'metacritic'
            - name: refresh-spotify-hourly
              sourceType: scheduler
              sourceDetails:
                cron: "0 * * * *"
                withBody:
                  resource: 'spotify'
