services:
  nginx:
    profiles: [ "prod" ]
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ../configs/nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ../certbot/www/:/var/www/certbot:ro
    depends_on:
      - zest-api
  adminer:
    profiles: [ "dev" ]
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080
  certbot:
    profiles: [ "certs" ]
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ../certbot/www/:/var/www/certbot:rw
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email reynaezekiel@gmail.com --agree-tos --no-eff-email -d api.zekereyna.dev

volumes:
  certbot-etc:
  certbot-var: