services:
  caddy:
    profiles: [ "prod" ]
    image: caddy:2.8.4 # latest version as of 10/4/24
    container_name: caddy
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    - 443:443/udp
    volumes:
    - ../configs/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
  adminer:
    profiles: [ "dev" ]
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080

volumes:
  caddy_data:
  caddy_config: