services:
  datadog:
    profiles: [ "monitoring" ]
    image: datadog/agent:latest
    container_name: dd-agent
    environment:
      - DD_API_KEY=__boop__
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_AGENT_HOST=dd-aggent
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:.*
      - DD_CONTAINER_INCLUDE=name:zest-api # TODO(zeke): temporary, exclude all except zest api
      #- DD_CONTAINER_EXCLUDE_LOGS="name:dd-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    ports:
      - 8125:8125
      - 8126:8126
      - 5000:5000 # should be the default port but not super sure.
