services:
  prometheus:
    profiles: [ "monitoring" ]
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - default
    depends_on:
      - zest-api
  grafana:
    profiles: [ "monitoring" ]
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
      - default
  tempo:
    profiles: [ "monitoring" ]
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    restart: unless-stopped
    volumes:
      - tempo-data:/tmp/tempo
      - ./configs/tempo.yaml:/etc/tempo.yaml
    networks:
      - monitoring
      - default
    ports:
      - 3200:3200 # tempo
      - 9095:9095 # tempo grpc
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http

volumes:
  prometheus-data:
  grafana-storage:
  tempo-data:

networks:
  monitoring:
    driver: bridge